### ISSUE TITLE
[Any chance for update?]

### ISSUE THREAD

**Issue by Rueby** [Frogworks-Interactive/EasySort#1]
Any chance this might be updated for 6.31?

**Comment by 53m1k0l0n** [comment]
You could use HaselTweaks as alternative.

**Comment by Rueby** [comment]
Oh cool didn't know that. ty

**Comment by codelastnight** [comment]
totally missed this omg 😵 This will be updated soon

**Comment by codelastnight** [comment]
updated and seems to work with path 6.4.
